spring:
  application:
    name: loan_calculator
  profiles:
    active: prod

server:
  port: 7123




jwt:
  secret: 9S7LYBue4yA1RpIah6x8rQYkeE1A9wL5YrkLEGybdAnzNTQ9tLlkU8XEvhz2kGOKXgU4n9ForQkLyucUAsEVGA==
  expiration: 86400000
